# Generated by Django 5.2.12 on 2026-05-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("reponse", models.TextField()),
                ("ordre", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "FAQ",
                "ordering": ["ordre"],
            },
        ),
    ]
