# Generated by Django 5.2.12 on 2026-05-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aapmarket", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "image_couverture",
                    models.ImageField(blank=True, null=True, upload_to="blog/covers/"),
                ),
                ("contenu", models.TextField()),
                (
                    "extrait",
                    models.TextField(
                        help_text="Petit texte pour l'aperçu sur la carte."
                    ),
                ),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("score_seo", models.IntegerField(default=0)),
                ("date_publication", models.DateTimeField(auto_now_add=True)),
                ("est_publie", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Article de Blog",
                "ordering": ["-date_publication"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                (
                    "type_demande",
                    models.CharField(
                        choices=[
                            ("PARTENARIAT", "Partenariat École"),
                            ("SUPPORT", "Support Technique"),
                            ("DEVIS", "Demande de Devis"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                ("est_lu", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Message de Contact",
                "ordering": ["-date_envoi"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                ("est_actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Abonné Newsletter",
            },
        ),
    ]
