"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import config
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-$dl316h&l+l6cx@w@%9om5c8jz^+gf8u!0ynb8*#kz!coh4izj"
SECRET_KEY=config("SECRET_KEY")
TEMPLATES_DIR=os.path.join(BASE_DIR,'templates')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="127.0.0.1", cast=lambda v: [s.strip() for s in v.split(',')])
PLAUSIBLE_API_KEY = config("PLAUSIBLE_API_KEY")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
     # Wagtail — ordre important
    # 'wagtail.contrib.forms',
    # 'wagtail.contrib.redirects',
    # 'wagtail.embeds',
    # 'wagtail.sites',
    # 'wagtail.users',
    # 'wagtail.snippets',
    # 'wagtail.documents',
    # 'wagtail.images',
    # 'wagtail.search',
    # 'wagtail.admin',
    'wagtail',
    'modelcluster',
    'taggit',
    "search",
    "theme",
    'tailwind',
    "accounts",
    "abonnements",
    "analytics",
     'django.contrib.sitemaps',
    'meta',
    'seo',
    'portfolio',
     'django_celery_beat',
    'django_celery_results',

]
# Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'default'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Ouagadougou'
#EMAIL LOCALHOST CONFIGURATION

#
WAGTAIL_SITE_NAME = 'WEBA'
TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = ['127.0.0.1']


META_SITE_PROTOCOL = 'http'
META_USE_OG_PROPERTIES = True
META_USE_TWITTER_PROPERTIES = True
META_DEFAULT_IMAGE = '/static/images/weba-og.png'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
                'wagtail.contrib.redirects.middleware.RedirectMiddleware',  
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATES_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
        'abonnements.context_processors.plan_utilisateur',  # ← ajoute
         'portfolio.context_processors.portfolio_tokens',

            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"
#
# Remplace le backend console par SMTP Gmail# --- CONFIGURATION EMAIL ---
EMAIL_BACKEND = config("EMAIL_BACKEND", default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config("EMAIL_HOST", default='smtp.gmail.com')
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
   'default': config(
       'DATABASE_URL',
       default=f"postgres://{config('DB_USER')}:{config('DB_PASSWORD')}@{config('DB_HOST')}:{config('DB_PORT')}/{config('DB_NAME')}",
       cast=lambda v: __import__('dj_database_url').parse(v) if v.startswith('postgres://') else {
           'ENGINE': 'django.db.backends.postgresql_psycopg2',
           'NAME': config('DB_NAME'),
           'USER': config('DB_USER'),
           'PASSWORD': config('DB_PASSWORD'),
           'HOST': config('DB_HOST'),
           'PORT': config('DB_PORT'),
       }
   )
}
#
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = "/assets/"
MEDIA_ROOT = os.path.join(BASE_DIR, "assets/")
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Rappels abonnements — tous les jours à 9h
    'rappel-abonnements': {
        'task': 'rappel_abonnement_expirant',
        'schedule': crontab(hour=9, minute=0),
    },
    # Régénération sitemap — tous les jours à 2h du matin
    'generer-sitemap': {
        'task': 'generer_sitemap',
        'schedule': crontab(hour=2, minute=0),
    },
    # Nettoyage sessions — tous les dimanches à 3h
    'nettoyer-sessions': {
        'task': 'nettoyer_sessions',
        'schedule': crontab(hour=3, minute=0, day_of_week=0),
    },
}