# Generated by Django 5.2.12 on 2026-04-06 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("ville", models.CharField(blank=True, max_length=100)),
                ("secteur", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("gratuit", "Gratuit"),
                            ("pro", "Pro"),
                            ("business", "Business"),
                        ],
                        default="gratuit",
                        max_length=20,
                    ),
                ),

                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
