# Generated by Django 5.2.12 on 2026-04-06 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        choices=[
                            ("gratuit", "Gratuit"),
                            ("pro", "Pro"),
                            ("business", "Business"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("prix_mensuel", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("templates_premium", models.BooleanField(default=False)),
                ("analytics_avances", models.BooleanField(default=False)),
                ("portfolio", models.BooleanField(default=False)),
                ("ia_branding", models.BooleanField(default=False)),
                ("app_web", models.BooleanField(default=False)),
                ("automatisations", models.BooleanField(default=False)),
                ("portfolio_equipe", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Plan",
            },
        ),
        migrations.CreateModel(
            name="DemandeUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuve", "Approuvé"),
                            ("refuse", "Refusé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                (
                    "reference_paiement",
                    models.CharField(
                        blank=True,
                        help_text="Référence du paiement Wave/Orange Money",
                        max_length=200,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan_demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="abonnements.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'upgrade",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.CreateModel(
            name="Abonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateTimeField(auto_now_add=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                ("actif", models.BooleanField(default=True)),
                ("reference_paiement", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonnement",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="abonnes",
                        to="abonnements.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement",
            },
        ),
    ]
