# Generated by Django 5.2.12 on 2026-04-06 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        help_text="Ex: Menuisier professionnel à Ouagadougou",
                        max_length=200,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Présentation détaillée de votre activité"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="portfolios/photos/"
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("email_contact", models.EmailField(blank=True, max_length=254)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("facebook", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("slug", models.SlugField(unique=True)),
                ("publie", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "couleur",
                    models.CharField(
                        choices=[
                            ("emerald", "Vert"),
                            ("blue", "Bleu"),
                            ("purple", "Violet"),
                            ("orange", "Orange"),
                            ("red", "Rouge"),
                        ],
                        default="emerald",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio",
            },
        ),
        migrations.CreateModel(
            name="MessageContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("message", models.TextField()),
                ("lu", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de contact",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Realisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="portfolios/realisations/"
                    ),
                ),
                ("lien", models.URLField(blank=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realisations",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réalisation",
                "ordering": ["ordre", "-date"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "prix",
                    models.CharField(
                        blank=True,
                        help_text="Ex: À partir de 5 000 FCFA",
                        max_length=100,
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="Temoignage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_client", models.CharField(max_length=100)),
                ("entreprise", models.CharField(blank=True, max_length=100)),
                ("contenu", models.TextField()),
                (
                    "note",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
                    ),
                ),
                ("approuve", models.BooleanField(default=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temoignages",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Témoignage",
                "ordering": ["-date"],
            },
        ),
    ]
