# Generated by Django 5.2.12 on 2026-04-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="template_choisi",
            field=models.CharField(
                choices=[
                    ("minimal", "Minimaliste (Expert)"),
                    ("showcase", "Showcase (Créatif)"),
                    ("business", "Accélérateur (Business)"),
                ],
                default="minimal",
                max_length=50,
            ),
        ),
    ]
