# Generated by Django 5.2.12 on 2026-04-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_portfolio_template_choisi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="template_choisi",
            field=models.CharField(
                choices=[
                    ("minimal", "Minimaliste (Expert)"),
                    ("showcase", "Showcase (Créatif)"),
                    ("business", "Accélérateur (Business)"),
                    ("onyx_impact", "Onyx Impact (Premium)"),
                    ("excellence", "Excellence (Premium)"),
                ],
                default="minimal",
                max_length=50,
            ),
        ),
    ]
