# Generated by Django 5.2.12 on 2026-04-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_alter_portfolio_template_choisi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="template_choisi",
            field=models.CharField(
                choices=[
                    ("minimal_blanc", "Minimaliste (Expert)"),
                    ("bold_coral", "Bold Coral (Premium)"),
                    ("minimal_luxury", "Minimal Luxury (Premium)"),
                    ("tech_slate", "Tech Slate (Premium)"),
                    ("afrique_moderne", "Afrique Moderne (Premium)"),
                ],
                default="minimal",
                max_length=50,
            ),
        ),
    ]
