# Generated by Django 5.2.12 on 2026-04-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_alter_portfolio_template_choisi"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="couleur_accent",
            field=models.CharField(default="#993C1D", max_length=7),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="couleur_fond",
            field=models.CharField(default="#FAFAF8", max_length=7),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="couleur_fond_2",
            field=models.CharField(default="#FAECE7", max_length=7),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="couleur_primaire",
            field=models.CharField(default="#D85A30", max_length=7),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="couleur_texte",
            field=models.CharField(default="#2C2C2A", max_length=7),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="police",
            field=models.CharField(
                choices=[
                    ("inter", "Inter — Moderne"),
                    ("georgia", "Georgia — Classique"),
                    ("poppins", "Poppins — Arrondi"),
                    ("playfair", "Playfair — Luxe"),
                    ("mono", "Monospace — Tech"),
                ],
                default="inter",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="rayon_bordure",
            field=models.CharField(
                choices=[
                    ("0px", "Carré — Strict"),
                    ("6px", "Légèrement arrondi"),
                    ("12px", "Arrondi — Standard"),
                    ("20px", "Très arrondi"),
                    ("9999px", "Pill — Maximal"),
                ],
                default="12px",
                max_length=10,
            ),
        ),
    ]
