# Generated by Django 5.2.12 on 2026-04-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_portfolio_couleur_accent_portfolio_couleur_fond_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="couleur",
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="template_choisi",
            field=models.CharField(
                choices=[
                    ("minimal_blanc", "Minimaliste (Expert)"),
                    ("bold_coral", "Bold Coral (Premium)"),
                    ("minimal_luxury", "Minimal Luxury (Premium)"),
                    ("tech_slate", "Tech Slate (Premium)"),
                    ("creative_can", "Creative Can (Premium)"),
                    ("tera_decor", "Tera Decor (Premium)"),
                    ("afrique_moderne", "Afrique Moderne (Premium)"),
                ],
                default="minimal_blanc",
                max_length=50,
            ),
        ),
    ]
