# Generated by Django 5.2.12 on 2026-04-15 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_remove_portfolio_couleur_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TemplateMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("image_preview", models.ImageField(upload_to="templates/previews/")),
                ("description_longue", models.TextField()),
                ("est_premium", models.BooleanField(default=False)),
                (
                    "prix_cfa",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "slug_technique",
                    models.CharField(
                        help_text="Le nom utilisé dans Portfolio.CHOIX_TEMPLATES",
                        max_length=50,
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates",
                        to="portfolio.categorietemplate",
                    ),
                ),
            ],
        ),
    ]
