# Generated by Django 5.2.12 on 2026-04-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_categorietemplate_templatemetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatemetadata",
            name="couleur_fond",
            field=models.CharField(default="#FFFFFF", max_length=20),
        ),
        migrations.AddField(
            model_name="templatemetadata",
            name="couleur_primaire",
            field=models.CharField(default="#000000", max_length=20),
        ),
        migrations.AddField(
            model_name="templatemetadata",
            name="police_nom",
            field=models.CharField(default="Inter", max_length=100),
        ),
    ]
