# Generated by Django 5.2.12 on 2026-04-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_templatemetadata_couleur_fond_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatemetadata",
            name="couleur_accent",
            field=models.CharField(default="#059669", max_length=20),
        ),
        migrations.AddField(
            model_name="templatemetadata",
            name="couleur_fond_2",
            field=models.CharField(default="#f8fafc", max_length=20),
        ),
        migrations.AddField(
            model_name="templatemetadata",
            name="couleur_texte",
            field=models.CharField(default="#0f172a", max_length=20),
        ),
        migrations.AddField(
            model_name="templatemetadata",
            name="police_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="templatemetadata",
            name="rayon_bordure",
            field=models.CharField(default="0.75rem", max_length=20),
        ),
        migrations.AlterField(
            model_name="templatemetadata",
            name="couleur_fond",
            field=models.CharField(default="#ffffff", max_length=20),
        ),
        migrations.AlterField(
            model_name="templatemetadata",
            name="couleur_primaire",
            field=models.CharField(default="#10b981", max_length=20),
        ),
    ]
