# Generated by Django 5.2.12 on 2026-04-17 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0023_alter_portfolio_template_choisi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chiffre",
                    models.CharField(
                        blank=True,
                        default="10",
                        help_text="Ex: 150, 10, 24k",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Mariages, Ans d'Expérience",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
    ]
