# Generated by Django 5.2.12 on 2026-04-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0024_statistique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="couleur_accent",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="couleur_fond",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="couleur_fond_2",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="couleur_primaire",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="couleur_texte",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
