# Generated by Django 5.2.12 on 2026-04-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0025_alter_portfolio_couleur_accent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="est_personnalise",
            field=models.BooleanField(default=False),
        ),
    ]
