# Generated by Django 5.2.12 on 2026-04-20 11:05

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0026_portfolio_est_personnalise"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=portfolio.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="realisation",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=portfolio.models.user_directory_path
            ),
        ),
    ]
