# Generated by Django 5.2.12 on 2026-04-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0027_service_image_alter_realisation_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagecontact",
            name="sujet",
            field=models.CharField(default="Demande de contact", max_length=200),
        ),
    ]
