# Generated by Django 5.2.12 on 2026-04-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0028_messagecontact_sujet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagecontact",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
