# Generated by Django 5.2.12 on 2026-04-23 11:58

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0029_alter_messagecontact_telephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=portfolio.models.user_directory_path
            ),
        ),
    ]
